agent-config:
  server-port: 7443
  caFile: /mnt/gw-disk/Go/src/github.com/OpenPlatformSDN/nuage-oci-plugin/samples/ca.crt
  certcaFile: /mnt/gw-disk/Go/src/github.com/OpenPlatformSDN/nuage-oci-plugin/samples/k8s-cri-o--20170926-1.pem
